#################################
# Original Author: Sravanthi Kota Venkata
#################################
RTBENCH_PATH=${TOP_DIR}/..

override CFLAGS += -D$(INPUT)

ifdef CHECK_OUTPUT #TODO: Maybe include this in the extended report
override CFLAGS+= -DCHECK -DGENERATE_OUTPUT
endif

include ${RTBENCH_PATH}/generator/rtbench.mk

COMMON_DIR := $(TOP_DIR)/common/c
TIMING_DIR := $(TOP_DIR)/cycles/$(BMARK)
BMARK_DIR := $(TOP_DIR)/benchmarks/$(BMARK)

#The options set below and specific to each benchmark. Disparity takes 2 input images, whereas Tracking can take any >1 input images =.

# Variables exported from the benchmark specific Makefiles:
# BMARK
# INPUT - sqcif/qcif/cif

# C source, data and result directory

C_DIR=$(BMARK_DIR)/src/c
DATA_DIR=$(BMARK_DIR)/data/$(INPUT)
C_RESULT=$(BMARK_DIR)/result

# Source files for C and Common folders (excluding the script_bmark.c files)
C_SRC := $(filter-out %script_$(BMARK).c,$(wildcard $(C_DIR)/*.c))
COMMON_SRC := $(wildcard $(COMMON_DIR)/*.c)

#object folders
COMMON_OBJECT=$(TOP_DIR)/common/object/$(notdir $(CROSS_COMPILE))$(notdir $(CC))
COMMON_OBJECT_G=$(TOP_DIR)/common/object/$(notdir $(CROSS_COMPILE))$(notdir $(CC))/debug
COMMON_OBJECT_PG=$(TOP_DIR)/common/object/$(notdir $(CROSS_COMPILE))$(notdir $(CC))/profile
C_OBJECT=$(BMARK_DIR)/object/$(notdir $(CROSS_COMPILE))$(notdir $(CC))
C_OBJECT_G=$(BMARK_DIR)/object/$(notdir $(CROSS_COMPILE))$(notdir $(CC))/debug
C_OBJECT_PG=$(BMARK_DIR)/object/$(notdir $(CROSS_COMPILE))$(notdir $(CC))/profile

# object files
COMMON_O=$(addprefix $(COMMON_OBJECT)/,$(notdir $(COMMON_SRC:.c=.o)))
COMMON_OG=$(addprefix $(COMMON_OBJECT_G)/,$(notdir $(COMMON_SRC:.c=.o)))
COMMON_OPG=$(addprefix $(COMMON_OBJECT_PG)/,$(notdir $(COMMON_SRC:.c=.o)))
C_O=$(addprefix $(C_OBJECT)/,$(notdir $(C_SRC:.c=.o)))
C_OG=$(addprefix $(C_OBJECT_G)/,$(notdir $(C_SRC:.c=.o)))
C_OPG=$(addprefix $(C_OBJECT_PG)/,$(notdir $(C_SRC:.c=.o)))

# RULES
EXE =
INCLUDES = -I$(COMMON_DIR) -I$(C_DIR)
COMPILE_C = $(CROSS_COMPILE)$(CC) $(CFLAGS) -O2 $(INCLUDES)
C_LIBS = $(LDFLAGS)
COMPILE_G = $(CROSS_COMPILE)$(CC) $(CFLAGS) -g $(INCLUDES)
COMPILE_PG = $(COMPILE_G) -pg

$(COMMON_OBJECT)/%.o: $(COMMON_DIR)/%.c
	@mkdir -p $(COMMON_OBJECT)
	@$(COMPILE_C) -c  $< -o $@ $(C_LIBS)

$(COMMON_OBJECT_G)/%.o: $(COMMON_DIR)/%.c
	@mkdir -p $(COMMON_OBJECT_G)
	@$(COMPILE_G) -c $< -o $@ $(C_LIBS)

$(COMMON_OBJECT_PG)/%.o: $(COMMON_DIR)/%.c
	@mkdir -p $(COMMON_OBJECT_PG)
	@$(COMPILE_PG) -c $< -o $@ $(C_LIBS)

$(C_OBJECT)/%.o: $(C_DIR)/%.c
	@mkdir -p $(C_OBJECT)
	@$(COMPILE_C) -c $< -o $@ $(C_LIBS)

$(C_OBJECT_G)/%.o: $(C_DIR)/%.c
	@mkdir -p $(C_OBJECT_G)
	@$(COMPILE_G) -c $< -o $@ $(C_LIBS)

$(C_OBJECT_PG)/%.o: $(C_DIR)/%.c
	@mkdir -p $(C_OBJECT_PG)
	@$(COMPILE_PG) -c $< -o $@ $(C_LIBS)

c-run: compile
	@echo -e "Data set\t\t- $(INPUT)"
	@mkdir -p $(TIMING_DIR)
	@./$(BMARK)$(EXE) $(BMARK_OPTIONS) -b $(DATA_DIR) -o $(C_RESULT) | tee -i $(TIMING_DIR)/C_$(INPUT).txt

debug: $(RTBENCH) $(COMMON_OG) $(C_OG)
	@echo Compiling Debug C Version of the benchmark
	@$(COMPILE_G) $(RTBENCH_O) $(COMMON_OG) $(C_OG) $(C_DIR)/script_$(BMARK).c -o $(BMARK)$(EXE)-debug $(C_LIBS)
	@$(COMPILE_G) -fsanitize=address $(RTBENCH_O) $(COMMON_OG) $(C_OG) $(C_DIR)/script_$(BMARK).c -o $(BMARK)$(EXE)-asan $(C_LIBS)
	$(STATICX_REQ)
	$(STATICX_CMD) $(BMARK)$(EXE)-debug $(BMARK)$(EXE)-debug.sx
	$(STATICX_CMD) $(BMARK)$(EXE)-asan $(BMARK)$(EXE)-asan.sx

debug-valgrind: debug
	@valgrind --leak-check=full -s ./$(BMARK)$(EXE)-debug $(BMARK_OPTIONS) -o $(C_RESULT)  -b $(DATA_DIR)

debug-gdb: debug
	@gdb --args ./$(BMARK)$(EXE)-debug $(BMARK_OPTIONS) -o $(C_RESULT)  -b $(DATA_DIR)

debug-asan: debug
	@./$(BMARK)$(EXE)-asan $(BMARK_OPTIONS) -o $(C_RESULT)  -b $(DATA_DIR)

profile: compile-prof
	@echo -e "Data set\t\t- $(INPUT)"
	@./$(BMARK)$(EXE)-profile $(BMARK_OPTIONS) -b $(DATA_DIR) -o $(C_RESULT)
	@gprof $(BMARK)$(EXE)-profile

compile: $(RTBENCH) $(C_O) $(COMMON_O)
	@echo -e "Benchmark\t\t- $(BMARK)"
	@$(COMPILE_C) $(RTBENCH_O) $(C_O) $(COMMON_O) $(C_DIR)/script_$(BMARK).c  -o $(BMARK)$(EXE) $(C_LIBS)
	$(STATICX_REQ)
	$(STATICX_CMD) $(BMARK)$(EXE) $(BMARK)$(EXE).sx

compile-prof: $(RTBENCH) $(C_OPG) $(COMMON_OPG)
	@echo
	@echo -e "Benchmark\t\t- $(BMARK)"
	@$(COMPILE_PG) $(RTBENCH_O) $(COMMON_PG) $(C_PG) $(C_DIR)/script_$(BMARK).c -o $(BMARK)$(EXE)-profile $(C_LIBS)
	$(STATICX_REQ)
	$(STATICX_CMD) $(BMARK)$(EXE)-profile $(BMARK)$(EXE)-profile.sx

all: c-run

clean:
	@-rm -f $(BMARK) $(BMARK)$(EXE) $(BMARK)$(EXE)-debug $(BMARK)$(EXE)-profile $(BMARK)$(EXE)-asan $(BMARK)$(EXE).sx $(COMMON_O) $(COMMON_OG) $(COMMON_OPG) $(C_O) $(C_OG) $(C_OPG)
