/** @file signal_utils.c
 * @ingroup generator
 * @brief Utility functions to setup a signal handler and a real-time timer.
 *
 * **Dependencies**:
 * - POSIX.4 real-time signals.
 *
 * @copyright (C) 2021 - 2022, Mattia Nicolella <mnico@bu.edu> and the rt-bench
 * contributors. SPDX-License-Identifier: MIT
 */

#include "signal_utils.h"
#include <stdio.h>
#include <string.h>

int setup_signal(int handled_signal, void (*handler)(int, siginfo_t *, void *),
                 int *masked_signals, int masked_signals_num) {
  struct sigaction sa;
  int res = 0, i;
  // we set the signals to ignore while handling the specified signal
  res = sigemptyset(&sa.sa_mask);
  if (res == -1) {
    perror("Error during sigemptyset for signal handler");
    return res;
  }
  // we mask the requested signals
  for (i = 0; i < masked_signals_num; i++) {
    res = sigaddset(&sa.sa_mask, masked_signals[i]);
    if (res == -1) {
      perror("Error during sigaddset for signal handler");
      return res;
    }
  }
  // install the signal handler.
  sa.sa_flags = SA_SIGINFO;
  sa.sa_sigaction = handler;
  res = sigaction(handled_signal, &sa, NULL);
  if (res == -1) {
    perror("Error during signal handler installation");
    return res;
  }
  return 0;
}

/**
 * @details
 * The function will create and arm the timer for a periodic execution, with the
 * specified timing. The timer will be armed immediately after creation.\n
 * `interval_sec` and `interval_nsec` can be used in conjunction to specify when
 * the timer must expire and if they are both set to `0` the timer will not be
 * armed.
 */
int setup_timer(timer_t *timer, int signal_generated, long interval_sec,
                long interval_nsec) {
  struct sigevent event;
  struct itimerspec timer_spec;
  int res = 0;
  memset(&event, 0, sizeof(event));
  // the timer will generate a signal
  event.sigev_notify = SIGEV_SIGNAL;
  // the signal generated by the timer
  event.sigev_signo = signal_generated;
  // creation of the timer
  res = timer_create(CLOCK_REALTIME, &event, timer);
  if (res != 0) {
    perror("Error during HR timer creation");
    return res;
  }
  // setting when the timer must be fired, using the provided deadline
  // parameters
  timer_spec.it_interval.tv_sec = interval_sec;
  timer_spec.it_interval.tv_nsec = interval_nsec;
  // the timer will start according to the setup deadline
  timer_spec.it_value.tv_sec = interval_sec;
  timer_spec.it_value.tv_nsec = interval_nsec;
  res = timer_settime(*timer, 0, &timer_spec, NULL);
  if (res < 0) {
    perror("Error during timer setup");
    return res;
  }
  return 0;
}
